name: ✨ Feature Request
description: Suggest a new feature for Field Station
title: "[FEATURE] "
labels: ["type:feature", "priority:medium"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide details below.

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area would this feature affect?
      options:
        - Crops & Plant Growth
        - Weather & Environment
        - User Interface
        - Simulation Engine
        - Educational Content
        - Data & Scientific Accuracy
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: A clear description of what you want to happen
      placeholder: Describe the feature in detail
    validations:
      required: true

  - type: textarea
    id: problem_solving
    attributes:
      label: Problem This Solves
      description: What problem does this feature solve?
      placeholder: Explain the problem or need this addresses
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions you've considered

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Critical for usability
    validations:
      required: true

  - type: dropdown
    id: educational_value
    attributes:
      label: Educational Value
      description: Does this feature enhance the educational aspect?
      options:
        - High - Significantly educational
        - Medium - Somewhat educational  
        - Low - Primarily entertainment
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples