name: 📋 Task
description: Create a development task or chore
title: "[TASK] "
labels: ["type:task"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Create a development task, maintenance item, or project chore.

  - type: dropdown
    id: area
    attributes:
      label: Task Area
      description: Which area does this task relate to?
      options:
        - Crops & Plant Growth
        - Weather & Environment
        - User Interface
        - Simulation Engine
        - Educational Content
        - Data & Scientific Accuracy
        - Performance
        - Documentation
        - Testing
        - DevOps/Infrastructure
        - Research
        - Other
    validations:
      required: true

  - type: textarea
    id: task_description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Describe the task clearly
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this task is complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Task priority level
      options:
        - Low
        - Medium
        - High
      default: 1
    validations:
      required: true

  - type: textarea
    id: related_issues
    attributes:
      label: Related Issues
      description: Link to any related issues or dependencies
      placeholder: "#123, #456"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information